import "./globals.css"
import { ThemeProvider } from "@/component/theme-provider"
import { cn } from "@/lib/utils"
import { AppSidebar } from "@/component/AppSidebar"
import Navbar from "@/component/Navbar"
import { SidebarProvider } from "@/component/ui/sidebar"
import { ProtectedRoute } from "@/component/ProtectedRoute"

import type { Metadata } from "next";
import { Inter, Playfair_Display, JetBrains_Mono } from "next/font/google";
import { cookies } from "next/headers"
import { DropdownMenuSeparator } from "@/component/ui/dropdown-menu"

const fontSans = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

const fontSerif = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-serif",
});

const fontMono = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export  default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {

  const cookieStore = await cookies();
  const defaultOpen = cookieStore.get("sidebar_state")?.value === "true";

  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={cn(
        "antialiased",
        fontSans.variable,
        fontSerif.variable,
        fontMono.variable
      )}
    >
      <body className="m-0 p-0 flex gap-1">
        <ThemeProvider>
          <SidebarProvider defaultOpen={defaultOpen}>
            <AppSidebar />
            <main className="w-full flex-col">
              <Navbar />
              <DropdownMenuSeparator />
              <ProtectedRoute>{children}</ProtectedRoute>
            </main>
          </SidebarProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
