import {
  Inter,
  Poppins,
  Noto_Serif_Georgian,
  JetBrains_Mono,
} from "next/font/google";
import "./globals.css";
import { ReduxProvider } from "@/redux/provider";
import { cookies } from "next/headers";

const fontSans = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

const fontPoppins = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

const fontSerif = Noto_Serif_Georgian({
  subsets: ["georgian"], // important for this font
  variable: "--font-serif",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

const fontMono = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-mono",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: Readonly<{
  children: React.ReactNode
}>) {
    const cookieStore = await cookies();
  const defaultOpen = cookieStore.get("sidebar_state")?.value === "true";


  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`antialiased ${fontSans.variable}
  ${fontPoppins.variable}
  ${fontSerif.variable}
  ${fontMono.variable} h-full antialiased`}
    >
      <body
        className={`${fontSans.variable} ${fontSerif.variable} ${fontMono.variable} ${fontPoppins.variable} antialiased`}
      >
        
        <ReduxProvider>{children}</ReduxProvider>
      </body>
    </html>
  );
}
